'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ArduCenter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _908545() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_908545", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avvio_1_011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avvio_1.011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avvio_1_3v() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avvio_1.3v", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Btn_Avanti_50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Avanti_50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Btn_Indietro_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Indietro_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Btn_Indietro_50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Indietro_50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_Swich() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn Swich", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_SwichON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_SwichON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnChiudi21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnChiudi21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnConnettiDisconnetti_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnConnettiDisconnetti 2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnDisconnettiConnetti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnDisconnettiConnetti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_CPU_OP_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_CPU_OP_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Audio_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Audio_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Audio_OFF1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Audio_OFF1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Audio_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Audio_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_CMD_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_CMD_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_CMD_ON_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_CMD_ON_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Impostazioni_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Impostazioni_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Impostazioni_ON_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Impostazioni_ON_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Task_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Task_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Fan_Task_ON_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Fan_Task_ON_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_GPU_Strip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_GPU_Strip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_GPU_Strip_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_GPU_Strip_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPage_Indietro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPage_Indietro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnFanPageNull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnFanPageNull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnGUI_Fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnGUI_Fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnGUI_Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnGUI_Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnGUI_HomeAudio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnGUI_HomeAudio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnGUI_HomeImpostazioni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnGUI_HomeImpostazioni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnGUI_HomeProject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnGUI_HomeProject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_DiscontinuoON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_DiscontinuoON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_halloween_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_halloween_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_halloween_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_halloween_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_MusicaON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_MusicaON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_RainBowON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_RainBowON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_Spento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_Spento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_SpentoON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_SpentoON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_Temperatura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_Temperatura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_TemperaturaON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_TemperaturaON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLED_TransizioneON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLED_TransizioneON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLuminositàMax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLuminositàMax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnLuminositàMin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnLuminositàMin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnNascondi2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnNascondi2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnVelocitàMax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnVelocitàMax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BtnVelocitàMin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnVelocitàMin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_Colore_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_Colore_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_Colore_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_Colore_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_Colore_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_Colore_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_Colore_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_Colore_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_HSV_v1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_HSV v1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dissipatore240mm_HSV_v1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dissipatore240mm_HSV_v1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_HardwareMonitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_HardwareMonitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_Home_2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_Home_2.3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_Impostazioni_HUB_Ventole_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_Impostazioni-HUB_Ventole_1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_Impostazioni_HUB_Ventole1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_Impostazioni-HUB_Ventole1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_ImpostazioniFan_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_ImpostazioniFan_1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F_ImpostazioniFan_1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_ImpostazioniFan_1.3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Funzioni_Dispositivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Funzioni_Dispositivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Funzioni_Dispositivo_Audio_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Funzioni_Dispositivo_Audio_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Funzioni_Dispositivo_Fan_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Funzioni_Dispositivo_Fan_1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Funzioni_Dispositivo_Null() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Funzioni_Dispositivo_Null", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Avviso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Avviso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_CMD_SerialFan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_CMD_SerialFan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Connessione2_0_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Connessione2.0.5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_F_Hub_PC_0_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_F_Hub_PC_0.1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_F_Hub_PC_0_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_F_Hub_PC_0.1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_F_HubPC_Home_0_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_F_HubPC_Home_0.1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_F_HubPC_Home_0_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_F_HubPC_Home_0.1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_F_HubPC_Home_0_1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_F_HubPC_Home_0.1.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan_2.3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_2_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_2_1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_2_v2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_2_v2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_2_v21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_2_v21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_3_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_3_1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_3_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_3_1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_Fan_Menù_4_v1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_Fan-Menù_4_v1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_HardwareMonitor_PC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_HardwareMonitor_PC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Cartella_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Cartella_1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Cartella_1_1_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Cartella_1_1_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB_1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB_1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB_1.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB_v1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB_v1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB_v1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB_v1.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB_v1.3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_HSV_RGB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_HSV_RGB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_RGB_Discontinuo_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_RGB_Discontinuo_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_RGB_Musica_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_RGB_Musica_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_RGB_RainBow_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_RGB_RainBow_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_DeepCool_RGB_Transizione_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_DeepCool_RGB_Transizione_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Fan_Dissipatore_RGB_Discontinuo_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Fan_Dissipatore_RGB_Discontinuo_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Fan_Dissipatore_RGB_Musica_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Fan_Dissipatore_RGB_Musica_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Fan_Dissipatore_RGB_RainBow_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Fan_Dissipatore_RGB_RainBow_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Fan_Dissipatore_RGB_Transizione_v1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Fan_Dissipatore_RGB_Transizione_v1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_FanPO_1_2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_FanPO_1.2 ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_FanPO_1_2_Click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_FanPO_1_2_Click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_FanPO_1_3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_FanPO_1.3 ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB 1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_1_1_RGB_Colore_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB_1_1_RGB_Colore_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_1_1_RGB_Colore_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB_1_1_RGB_Colore_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_1_1_RGB_Colore_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB_1_1_RGB_Colore_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_1_1_RGB_Colore_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB_1_1_RGB_Colore_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_HUB_v1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_HUB v1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Parametri_Fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Parametri_Fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Parametri_FanON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Parametri_FanON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Reset_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Reset_1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Riavvio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Riavvio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_ROM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_ROM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Arancione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Arancione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Azzurro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Azzurro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Bianco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Bianco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Blu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Blu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Effeto_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Effeto_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Effeto_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Effeto_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Effeto_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Effeto_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Effeto_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Effeto_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Fucsia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Fucsia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Giallo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Giallo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Nero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Nero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_RGB_Colore_HSV_RGB_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_RGB_Colore_HSV-RGB_2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_RGB_Colore_HSV_RGB_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_RGB_Colore_HSV-RGB_2.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_RGB_Colore_HSV_RGB_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_RGB_Colore_HSV-RGB_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Rosso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Rosso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_SchedaVideo_Verde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_SchedaVideo_Verde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca__RGB_Colore_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_HSV_RGB_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca _RGB_Colore_HSV-RGB_2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_HSV_RGB_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca _RGB_Colore_HSV-RGB_2.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_HSV_RGB_2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca _RGB_Colore_HSV-RGB_2.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_HSV_RGB_2_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca _RGB_Colore_HSV-RGB_2.2.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_HSV_RGB_2_2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca _RGB_Colore_HSV-RGB_2.2.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca__RGB_Colore_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca__RGB_Colore_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca__RGB_Colore_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca__RGB_Colore_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Arancione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Arancione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Azzurro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Azzurro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Bianco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Bianco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Blu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Blu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Fucsia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Fucsia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Giallo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Giallo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Nero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca LED Nero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Rosso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Rosso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icona_Strisca_LED_Verde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icona_Strisca_LED_Verde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaCasaAudio_RGB_Colore_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaCasaAudio_RGB_Colore_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaCasaAudio_RGB_Colore_HSV_RGB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaCasaAudio_RGB_Colore_HSV-RGB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaCasaAudio_RGB_Colore_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaCasaAudio_RGB_Colore_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaCasaAudio_RGB_Colore_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaCasaAudio_RGB_Colore_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaCasaAudio_RGB_Colore_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaCasaAudio_RGB_Colore_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB__Nero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB _Nero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Arancio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Arancio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Azzurro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Azzurro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Bianco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Bianco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Blu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Blu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Discontinuo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Discontinuo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Fucsia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Fucsia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Giallo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Giallo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_HSV_RGB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_HSV-RGB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_HSV_RGB_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_HSV-RGB_2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Musica_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Musica_2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Nero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Nero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_RainBow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_RainBow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Rosso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Rosso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Transizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Transizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Transizione_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Transizione_2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaFan_RGB_Colore_Verde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaFan_RGB_Colore_Verde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaHardware_AMD_CPU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaHardware_AMD_CPU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaHardware_AMD_GPU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaHardware_AMD_GPU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaHardware_RAM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaHardware_RAM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconaHubStruments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconaHubStruments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icone_ProtezioneDispositivo_2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icone_ProtezioneDispositivo_2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icone_ProtezioneLED_1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icone_ProtezioneLED_1.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgArduCenter2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgArduCenter2.0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Incona_Comandi_Fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Incona_Comandi_Fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Incona_Comandi_FanON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Incona_Comandi_FanON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property opt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("opt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PanSetHardware_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PanSetHardware_1.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
